language: csharp
solution: PartyNow.Mobile.sln
install:
  - nuget restore PartyNow.Mobile.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PartyNow.Mobile.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./test/PartyNow.DataContract.Tests/bin/Release/PartyNow.DataContract.Tests.dll
